cat in/0000.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0000.txt
cat in/0001.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0001.txt
cat in/0002.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0002.txt
cat in/0003.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0003.txt
cat in/0004.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0004.txt
cat in/0005.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0005.txt
cat in/0006.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0006.txt
cat in/0007.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0007.txt
cat in/0008.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0008.txt
cat in/0009.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0009.txt
cat in/0010.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0010.txt
cat in/0011.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0011.txt
cat in/0012.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0012.txt
cat in/0013.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0013.txt
cat in/0014.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0014.txt
cat in/0015.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0015.txt
cat in/0016.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0016.txt
cat in/0017.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0017.txt
cat in/0018.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0018.txt
cat in/0019.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0019.txt
cat in/0020.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0020.txt
cat in/0021.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0021.txt
cat in/0022.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0022.txt
cat in/0023.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0023.txt
cat in/0024.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0024.txt
cat in/0025.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0025.txt
cat in/0026.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0026.txt
cat in/0027.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0027.txt
cat in/0028.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0028.txt
cat in/0029.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0029.txt
cat in/0030.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0030.txt
cat in/0031.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0031.txt
cat in/0032.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0032.txt
cat in/0033.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0033.txt
cat in/0034.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0034.txt
cat in/0035.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0035.txt
cat in/0036.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0036.txt
cat in/0037.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0037.txt
cat in/0038.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0038.txt
cat in/0039.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0039.txt
cat in/0040.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0040.txt
cat in/0041.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0041.txt
cat in/0042.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0042.txt
cat in/0043.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0043.txt
cat in/0044.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0044.txt
cat in/0045.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0045.txt
cat in/0046.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0046.txt
cat in/0047.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0047.txt
cat in/0048.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0048.txt
cat in/0049.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0049.txt
cat in/0050.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0050.txt
cat in/0051.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0051.txt
cat in/0052.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0052.txt
cat in/0053.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0053.txt
cat in/0054.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0054.txt
cat in/0055.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0055.txt
cat in/0056.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0056.txt
cat in/0057.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0057.txt
cat in/0058.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0058.txt
cat in/0059.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0059.txt
cat in/0060.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0060.txt
cat in/0061.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0061.txt
cat in/0062.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0062.txt
cat in/0063.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0063.txt
cat in/0064.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0064.txt
cat in/0065.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0065.txt
cat in/0066.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0066.txt
cat in/0067.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0067.txt
cat in/0068.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0068.txt
cat in/0069.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0069.txt
cat in/0070.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0070.txt
cat in/0071.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0071.txt
cat in/0072.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0072.txt
cat in/0073.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0073.txt
cat in/0074.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0074.txt
cat in/0075.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0075.txt
cat in/0076.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0076.txt
cat in/0077.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0077.txt
cat in/0078.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0078.txt
cat in/0079.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0079.txt
cat in/0080.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0080.txt
cat in/0081.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0081.txt
cat in/0082.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0082.txt
cat in/0083.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0083.txt
cat in/0084.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0084.txt
cat in/0085.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0085.txt
cat in/0086.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0086.txt
cat in/0087.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0087.txt
cat in/0088.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0088.txt
cat in/0089.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0089.txt
cat in/0090.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0090.txt
cat in/0091.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0091.txt
cat in/0092.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0092.txt
cat in/0093.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0093.txt
cat in/0094.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0094.txt
cat in/0095.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0095.txt
cat in/0096.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0096.txt
cat in/0097.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0097.txt
cat in/0098.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0098.txt
cat in/0099.txt | cargo run --release --bin tester python ..\A\main.py > .\out\0099.txt